//
//  XPBarKit.swift
//  SaveTheBird
//
//  Created by Daniel Peters on 11.08.15.
//  Copyright (c) 2015 TapAdventures. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

open class XPBarKit : NSObject {

    //// Drawing Methods

    open class func drawXPBar(frame: CGRect, xP: CGFloat, level: CGFloat) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Color Declarations
        let grey = UIColor(red: 0.855, green: 0.855, blue: 0.855, alpha: 1.000)
        let green = UIColor(red: 0.000, green: 1.000, blue: 0.000, alpha: 1.000)

        //// Variable Declarations
        let neededXP: CGFloat = level * level * 100
        //let progressBar_text = "\(Int(round(xP)))" + " / " + "\(Int(round(neededXP)))" + " XP for Level: " + "\(Int(round(level + 1)))"
        let progressBar_text = GlobalFunctions().formatNumber(Int(xP)) + " / " + GlobalFunctions().formatNumber(Int(neededXP)) + " XP for Level: " + GlobalFunctions().formatNumber(Int(level)+1)
        let levelProgress: CGFloat = xP / neededXP
        let progressBar: CGFloat = levelProgress * frame.width

        //// BackBar Drawing
        let backBarPath = UIBezierPath(roundedRect: CGRect(x: frame.minX + floor(frame.width * 0.00000 + 0.5), y: frame.minY + floor(frame.height * 0.00000 + 0.5), width: floor(frame.width * 1.00000 + 0.5) - floor(frame.width * 0.00000 + 0.5), height: floor(frame.height * 0.90909 + 0.5) - floor(frame.height * 0.00000 + 0.5)), byRoundingCorners: [UIRectCorner.bottomLeft, UIRectCorner.bottomRight], cornerRadii: CGSize(width: 5, height: 5))
        backBarPath.close()
        grey.setFill()
        backBarPath.fill()


        //// XpBar Drawing
        //let xpBarPath = UIBezierPath(roundedRect: CGRectMake(0, 0, progressBar, 10), byRoundingCorners: [UIRectCorner.BottomLeft, UIRectCorner.BottomRight], cornerRadii: CGSizeMake(0.5, 0.5))
        //xpBarPath.closePath()
        let xpBarPath = UIBezierPath(roundedRect: CGRect(x: frame.minX + floor(frame.width * 0.00000 + 0.5), y: frame.minY + floor(frame.height * 0.00000 + 0.5), width: progressBar, height: floor(frame.height * 0.90909 + 0.5) - floor(frame.height * 0.00000 + 0.5)), byRoundingCorners: [UIRectCorner.bottomLeft, UIRectCorner.bottomRight], cornerRadii: CGSize(width: 5, height: 5))
        green.setFill()
        xpBarPath.fill()


        //// Text Drawing
        let textRect = CGRect(x: frame.minX + floor(frame.width * 0.00000 + 0.5), y: frame.minY + floor(frame.height * 0.00000 + 0.5), width: floor(frame.width * 1.00000 + 0.5) - floor(frame.width * 0.00000 + 0.5), height: floor(frame.height * 0.90909 + 0.5) - floor(frame.height * 0.00000 + 0.5))
        let textStyle = NSParagraphStyle.default.mutableCopy() as! NSMutableParagraphStyle
        textStyle.alignment = NSTextAlignment.center

        let textFontAttributes = [NSFontAttributeName: UIFont(name: "Chalkduster", size: 9)!, NSForegroundColorAttributeName: UIColor.black, NSParagraphStyleAttributeName: textStyle]

        let textTextHeight: CGFloat = NSString(string: progressBar_text).boundingRect(with: CGSize(width: textRect.width, height: CGFloat.infinity), options: NSStringDrawingOptions.usesLineFragmentOrigin, attributes: textFontAttributes, context: nil).size.height
        context?.saveGState()
        context?.clip(to: textRect);
        NSString(string: progressBar_text).draw(in: CGRect(x: textRect.minX, y: textRect.minY + (textRect.height - textTextHeight) / 2, width: textRect.width, height: textTextHeight), withAttributes: textFontAttributes)
        context?.restoreGState()
    }

    //// Generated Images

    open class func imageOfXPBar(frame: CGRect, xP: CGFloat, level: CGFloat) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(frame.size, false, 0)
            XPBarKit.drawXPBar(frame: frame, xP: xP, level: level)

        let imageOfXPBar = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return imageOfXPBar
    }

}
